### ISSUE TITLE
Add documentation for pre-specified planning

### ISSUE THREAD

**Issue by willu47** [nismod/smif#356]
In each year, the smif wrapper wipes the database tables clean, and writes in both past and future interventions.

To add you technologies into the future years you need to:

1 - add a pre-specified planning strategy to the model run config
```yaml
strategies:
- type: pre-specified-planning
  description:future energy plan
  filename: ../energy_supply/strategies/plan.csv
```

2 - Put this file `../energy_supply/strategies/plan.csv` in the `data/energy_supply/strategies/` folder
And ensure that `plan.csv` looks like this:
```csv
name,build_year
intervention_name,2030
```

With as many rows as interventions you want to add.
Finally…

3 - Update the `data/energy_supply/interventions/ *.csv` files with the interventions you reference in the strategy

also strategy.csv `name` and intervention.csv `name` should match
